author: Zhuowei
database: false
description: Implementation of the Minecraft PI modding API
main: net.zhuoweizhang.raspberryjuice.RaspberryJuicePlugin
name: RaspberryJuice
startup: postworld
version: '26.2'
api-version: 26.1.2
